#!/usr/bin/env sh
#
# Copyright 2026 The Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

real_npx="$(command -v npx || true)"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-install|-y|--yes)
      shift
      continue
      ;;
    postcss)
      shift
      exec postcss "$@"
      ;;
    *)
      break
      ;;
  esac
done

if [ -n "$real_npx" ]; then
  exec "$real_npx" "$@"
fi

printf 'Error: npx fallback is unavailable and postcss was not requested.\n' >&2
exit 127